export const technologies = [
  { name: 'React', logo: '/logos/react.svg' },
  { name: 'Next.js', logo: '/logos/nextjs.svg' },
  { name: 'TypeScript', logo: '/logos/typescript.svg' },
  { name: 'JavaScript', logo: '/logos/javascript.svg' },
  { name: 'Tailwind CSS', logo: '/logos/tailwindcss.svg' },
  { name: 'Redux', logo: '/logos/redux.svg' },
  { name: 'Node.js', logo: '/logos/nodejs.svg' },
  { name: 'Express', logo: '/logos/express.svg' },
  { name: 'PostgreSQL', logo: '/logos/postgresql.svg' },
  { name: 'MongoDB', logo: '/logos/mongodb.svg' },
  { name: 'Supabase', logo: '/logos/supabase.svg' },
  { name: 'Prisma', logo: '/logos/prisma.svg' },
  { name: 'Redis', logo: '/logos/redis.svg' },
  { name: 'Docker', logo: '/logos/docker.svg' },
  { name: 'WebSockets', logo: '/logos/websockets.svg' },
  { name: 'Git', logo: '/logos/git.svg' },
  { name: 'GitHub', logo: '/logos/github.svg' },
  { name: 'Vercel', logo: '/logos/vercel.svg' },
  { name: 'Postman', logo: '/logos/postman.svg' },
  { name: 'Figma', logo: '/logos/figma.svg' },
];
